/* eslint-disable */
// @ts-nocheck
// Code generated by protoc-gen-ts. DO NOT EDIT.
// versions:
// 	protoc-gen-ts v0.8.0
// 	protoc        v3.15.6
// source: audio2face.proto

import * as jspb from "google-protobuf";

export class AudioRequest extends jspb.Message {
  getAudioFilePath(): string;
  setAudioFilePath(value: string): AudioRequest;

  serializeBinary(): Uint8Array;
  toObject(includeInstance?: boolean): AudioRequest.AsObject;
  static toObject(includeInstance: boolean, msg: AudioRequest): AudioRequest.AsObject;
  static serializeBinaryToWriter(message: AudioRequest, writer: jspb.BinaryWriter): void;
  static deserializeBinary(bytes: Uint8Array): AudioRequest;
  static deserializeBinaryFromReader(message: AudioRequest, reader: jspb.BinaryReader): AudioRequest;
}

export namespace AudioRequest {
  export type AsObject = {
    audioFilePath: string,
  }
}

export class AnimationData extends jspb.Message {
  getWeightsList(): Array<number>;
  setWeightsList(value: Array<number>): AnimationData;
  clearWeightsList(): AnimationData;
  addWeights(value: number, index?: number): AnimationData;

  getRotationsList(): Array<number>;
  setRotationsList(value: Array<number>): AnimationData;
  clearRotationsList(): AnimationData;
  addRotations(value: number, index?: number): AnimationData;

  getTranslationsList(): Array<number>;
  setTranslationsList(value: Array<number>): AnimationData;
  clearTranslationsList(): AnimationData;
  addTranslations(value: number, index?: number): AnimationData;

  serializeBinary(): Uint8Array;
  toObject(includeInstance?: boolean): AnimationData.AsObject;
  static toObject(includeInstance: boolean, msg: AnimationData): AnimationData.AsObject;
  static serializeBinaryToWriter(message: AnimationData, writer: jspb.BinaryWriter): void;
  static deserializeBinary(bytes: Uint8Array): AnimationData;
  static deserializeBinaryFromReader(message: AnimationData, reader: jspb.BinaryReader): AnimationData;
}

export namespace AnimationData {
  export type AsObject = {
    weightsList: Array<number>,
    rotationsList: Array<number>,
    translationsList: Array<number>,
  }
}
