/* eslint-disable */
// @ts-nocheck
// Code generated by protoc-gen-ts. DO NOT EDIT.
// versions:
// 	protoc-gen-ts v0.8.0
// 	protoc        v3.15.6
// source: audio2face.proto

import * as grpc from "@grpc/grpc-js";
import * as audio2face_pb from "./audio2face_pb";

interface IAudio2FaceService extends grpc.ServiceDefinition<grpc.UntypedServiceImplementation> {
  streamAnimationData: grpc.MethodDefinition<audio2face_pb.AudioRequest, audio2face_pb.AnimationData>;
}

export const Audio2FaceService: IAudio2FaceService;

export interface IAudio2FaceServer extends grpc.UntypedServiceImplementation {
  streamAnimationData: grpc.handleServerStreamingCall<audio2face_pb.AudioRequest, audio2face_pb.AnimationData>;
}

export class Audio2FaceClient extends grpc.Client {
  constructor(address: string, credentials: grpc.ChannelCredentials, options?: object);
  streamAnimationData(argument: audio2face_pb.AudioRequest, metadataOrOptions?: grpc.Metadata | grpc.CallOptions | null): grpc.ClientReadableStream<audio2face_pb.AnimationData>;
  streamAnimationData(argument: audio2face_pb.AudioRequest, metadata?: grpc.Metadata | null, options?: grpc.CallOptions | null): grpc.ClientReadableStream<audio2face_pb.AnimationData>;
}
