import sys
import os

script_dir = os.path.dirname(os.path.abspath(__file__))
if script_dir not in sys.path:
    sys.path.append(script_dir)

from count_shapekeys_number import count_shapekeys_number

count_shapekeys_number()

audio2faceFacsNames = [
    "eyeBlinkLeft",
    "eyeLookDownLeft",
    "eyeLookInLeft",
    "eyeLookOutLeft",
    "eyeLookUpLeft",
    "eyeSquintLeft",
    "eyeWideLeft",
    "eyeBlinkRight",
    "eyeLookDownRight",
    "eyeLookInRight",
    "eyeLookOutRight",
    "eyeLookUpRight",
    "eyeSquintRight",
    "eyeWideRight",
    "jawForward",
    "jawLeft",
    "jawRight",
    "jawOpen",
    "mouthClose",
    "mouthFunnel",
    "mouthPucker",
    "mouthLeft",
    "mouthRight",
    "mouthSmileLeft",
    "mouthSmileRight",
    "mouthFrownLeft",
    "mouthFrownRight",
    "mouthDimpleLeft",
    "mouthDimpleRight",
    "mouthStretchLeft",
    "mouthStretchRight",
    "mouthRollLower",
    "mouthRollUpper",
    "mouthShrugLower",
    "mouthShrugUpper",
    "mouthPressLeft",
    "mouthPressRight",
    "mouthLowerDownLeft",
    "mouthLowerDownRight",
    "mouthUpperUpLeft",
    "mouthUpperUpRight",
    "browDownLeft",
    "browDownRight",
    "browInnerUp",
    "browOuterUpLeft",
    "browOuterUpRight",
    "cheekPuff",
    "cheekSquintLeft",
    "cheekSquintRight",
    "noseSneerLeft",
    "noseSneerRight",
    "tongueOut",
]

audio2faceEmotionNames = [
    "amazement",
    "anger",
    "cheekiness",
    "disgust",
    "fear",
    "grief",
    "joy",
    "outofbreath",
    "pain",
    "sadness",
]

shape_keys_cleaned_with_expresions_visemes = [
    "head_bs_AsymmetryEyelidsCreaseHeightLeft",
    "head_bs_AsymmetryEyelidsCreaseHeightRight",
    "head_bs_AsymmetryEyelidsLowerRelaxLeft",
    "head_bs_AsymmetryEyelidsLowerRelaxRight",
    "head_bs_AsymmetryEyelidsUpperRelaxLeft",
    "head_bs_AsymmetryEyelidsUpperRelaxRight",
    "head_bs_AsymmetryJawHorizontalBalance",
    "facs_BrowDownLeft",
    "facs_BrowDownRight",
    "facs_bs_BrowInnerUpLeft",
    "facs_bs_BrowInnerUpRight",
    "facs_BrowOuterUpLeft",
    "facs_BrowOuterUpRight",
    "facs_bs_BrowSqueezeLeft",
    "facs_bs_BrowSqueezeRight",
    "facs_bs_CheekHollowLeft",
    "facs_bs_CheekHollowRight",
    "facs_bs_CheekInflateCounterLeft",
    "facs_bs_CheekInflateCounterRight",
    "facs_bs_CheekInflateLeft",
    "facs_bs_CheekInflateRight",
    "facs_bs_CheekPuffLeft",
    "facs_bs_CheekPuffRight",
    "facs_bs_CheekSquintLeft",
    "facs_bs_CheekSquintRight",
    "facs_bs_EyeCornerTightnessInnerLeft",
    "facs_bs_EyeCornerTightnessInnerRight",
    "facs_bs_EyeCornerTightnessOuterLeft",
    "facs_bs_EyeCornerTightnessOuterRight",
    "facs_bs_EyeLidCloseUpperLeft",
    "facs_bs_EyeLookDownLeft",
    "facs_bs_EyeLookDownRight",
    "facs_bs_EyeLookInLeft",
    "facs_bs_EyeLookInRight",
    "facs_bs_EyeLookOutLeft",
    "facs_bs_EyeLookOutRight",
    "facs_bs_EyeLookUpLeft",
    "facs_bs_EyeLookUpRight",
    "facs_bs_EyeSquintLeft",
    "facs_bs_EyeSquintRight",
    "facs_bs_EyelidCloseLowerLeft",
    "facs_bs_EyelidCloseLowerRight",
    "facs_bs_EyelidCloseUpperRight",
    "facs_bs_EyelidOpenLowerLeft",
    "facs_bs_EyelidOpenLowerRight",
    "facs_bs_EyelidOpenUpperLeft",
    "facs_bs_EyelidOpenUpperRight",
    "facs_bs_JawChinCompression",
    "facs_bs_JawClenchLeft",
    "facs_bs_JawClenchRight",
    "facs_bs_JawLeft",
    "facs_bs_JawOpen",
    "facs_bs_JawOpenWide",
    "facs_bs_JawRecess",
    "facs_bs_JawRight",
    "facs_bs_MouthBackLowerLeft",
    "facs_bs_MouthBackLowerRight",
    "facs_bs_MouthBackUpperLeft",
    "facs_bs_MouthBackUpperRight",
    "facs_bs_MouthCloseLowerLeft",
    "facs_bs_MouthCloseLowerRight",
    "facs_bs_MouthCloseUpperLeft",
    "facs_bs_MouthCloseUpperRight",
    "facs_bs_MouthCompressLowerLeft",
    "facs_bs_MouthCompressLowerRight",
    "facs_bs_MouthCompressUpperLeft",
    "facs_bs_MouthCompressUpperRight",
    "facs_bs_MouthCornerMoveFwd-BackLeft",
    "facs_bs_MouthCornerMoveFwd-BackRight",
    "facs_bs_MouthCornerMoveSide-SideLeft",
    "facs_bs_MouthCornerMoveSide-SideRight",
    "facs_bs_MouthCornerMoveUp-DownLeft",
    "facs_bs_MouthCornerMoveUp-DownRight",
    "facs_bs_MouthCornerTightnessLowerLeft",
    "facs_bs_MouthCornerTightnessLowerRight",
    "facs_bs_MouthCornerTightnessUpperLeft",
    "facs_bs_MouthCornerTightnessUpperRight",
    "facs_bs_MouthDimpleLeft",
    "facs_bs_MouthDimpleRight",
    "facs_bs_MouthForward-BackMiddleLower",
    "facs_bs_MouthForward-BackMiddleUpper",
    "facs_bs_MouthForwardLowerLeft",
    "facs_bs_MouthForwardLowerRight",
    "facs_bs_MouthForwardUpperLeft",
    "facs_bs_MouthForwardUpperRight",
    "facs_bs_MouthFrownLeft",
    "facs_bs_MouthFrownRight",
    "facs_bs_MouthFunnelLowerLeft",
    "facs_bs_MouthFunnelLowerRight",
    "facs_bs_MouthFunnelUpperLeft",
    "facs_bs_MouthFunnelUpperRight",
    "facs_bs_MouthLeft",
    "facs_bs_MouthLipsSide-SideLower",
    "facs_bs_MouthLipsSide-SideUpper",
    "facs_bs_MouthLipVolumeLowerLeft",
    "facs_bs_MouthLipVolumeLowerRight",
    "facs_bs_MouthLipVolumeUpperLeft",
    "facs_bs_MouthLipVolumeUpperRight",
    "facs_bs_MouthLowerDownLeft",
    "facs_bs_MouthLowerDownRight",
    "facs_bs_MouthPressLowerLeft",
    "facs_bs_MouthPressLowerRight",
    "facs_bs_MouthPressUpperLeft",
    "facs_bs_MouthPressUpperRight",
    "facs_bs_MouthPurseLowerLeft",
    "facs_bs_MouthPurseLowerRight",
    "facs_bs_MouthPurseUpperLeft",
    "facs_bs_MouthPurseUpperRight",
    "facs_bs_MouthRight",
    "facs_bs_MouthRollLowerLeft",
    "facs_bs_MouthRollLowerRight",
    "facs_bs_MouthRollUpperLeft",
    "facs_bs_MouthRollUpperRight",
    "facs_bs_MouthShrugLowerLeft",
    "facs_bs_MouthShrugLowerRight",
    "facs_bs_MouthShrugUpperLeft",
    "facs_bs_MouthShrugUpperRight",
    "facs_bs_MouthSmileLeft",
    "facs_bs_MouthSmileRight",
    "facs_bs_MouthSmileWidenLeft",
    "facs_bs_MouthSmileWidenRight",
    "facs_bs_MouthStickyLowerCenter",
    "facs_bs_MouthStickyLowerInnerLeft",
    "facs_bs_MouthStickyLowerInnerRight",
    "facs_bs_MouthStickyLowerOuterLeft",
    "facs_bs_MouthStickyLowerOuterRight",
    "facs_bs_MouthStickyUpperCenter",
    "facs_bs_MouthStickyUpperInnerLeft",
    "facs_bs_MouthStickyUpperInnerRight",
    "facs_bs_MouthStretchLeft",
    "facs_bs_MouthStretchRight",
    "facs_bs_MouthUp-Down",
    "facs_bs_MouthUp-DownMiddleLower",
    "facs_bs_MouthUp-DownMiddleUpper",
    "facs_bs_MouthUpperUpLeft",
    "facs_bs_MouthUpperUpRight",
    "facs_bs_NasalCompressLeft",
    "facs_bs_NasalCompressRight",
    "facs_bs_NasalCreaseFlexLeft",
    "facs_bs_NasalCreaseFlexRight",
    "facs_bs_NasalFlareLeft",
    "facs_bs_NasalFlareRight",
    "facs_bs_NasalStretchLeft",
    "facs_bs_NasalStretchRight",
    "facs_bs_NeckFlexLeft",
    "facs_bs_NeckFlexRight",
    "facs_bs_NeckLarynxUp",
    "facs_bs_NeckMastoidFlexLeft",
    "facs_bs_NeckMastoidFlexRight",
    "facs_bs_NeckUnderChinFlex",
    "facs_bs_NoseSneerLeft",
    "facs_bs_NoseSneerRight",
    "facs_bs_NoseSneerUpperLeft",
    "facs_bs_NoseSneerUpperRight",
    "FACSDetails_facs_bs_BIU_BOULeft_HD2",
    "FACSDetails_facs_bs_BIU_BOURight_HD2",
    "FACSDetails_facs_bs_BrowDownLeft_HD2",
    "FACSDetails_facs_bs_BrowDownRight_HD2",
    "FACSDetails_facs_bs_BrowInnerUpLeft_HD2",
    "FACSDetails_facs_bs_BrowInnerUpRight_HD2",
    "FACSDetails_facs_bs_BrowOuterUpLeft_HD2",
    "FACSDetails_facs_bs_BrowOuterUpRight_HD2",
    "FACSDetails_facs_bs_BrowSqueezeLeft_HD2",
    "FACSDetails_facs_bs_BrowSqueezeRight_HD2",
    "FACSDetails_facs_bs_CheekSquintLeft_HD2",
    "FACSDetails_facs_bs_CheekSquintRight_HD2",
    "FACSDetails_facs_bs_EyeSquintLeft_HD2",
    "FACSDetails_facs_bs_EyeSquintRight_HD2",
    "FACSDetails_facs_bs_JawChinCompression_HD2",
    "FACSDetails_facs_bs_MouthFrownLeft_HD2",
    "FACSDetails_facs_bs_MouthFrownRight_HD2",
    "FACSDetails_facs_bs_MouthPurseLowerLeft_HD2",
    "FACSDetails_facs_bs_MouthPurseLowerRight_HD2",
    "FACSDetails_facs_bs_MouthPurseUpperLeft_HD2",
    "FACSDetails_facs_bs_MouthPurseUpperRight_HD2",
    "FACSDetails_facs_bs_MouthShrugLowerLeft_HD2",
    "FACSDetails_facs_bs_MouthShrugLowerRight_HD2",
    "FACSDetails_facs_bs_NoseSneerLeft_HD2",
    "FACSDetails_facs_bs_NoseSneerRight_HD2",
    "FACSDetails_facs_bs_NoseSneerUpperLeft_HD2",
    "FACSDetails_facs_bs_NoseSneerUpperRight_HD2",
    "body_bs_FlexBicepsL",
    "body_bs_FlexBicepsR",
    "body_bs_FlexShoulderUpperBackL",
    "body_bs_FlexShoulderUpperBackR",
    "body_bs_FlexTricepsL",
    "body_bs_FlexTricepsR",
    "body_cbs_forearm_y135n_l",
    "body_cbs_forearm_y135p_r",
    "body_cbs_forearm_y75n_l",
    "body_cbs_forearm_y75p_r",
    "body_cbs_hand_y28n_l",
    "body_cbs_hand_y28p_r",
    "body_cbs_hand_z70n_l",
    "body_cbs_hand_z70p_r",
    "body_cbs_hand_z80n_r",
    "body_cbs_hand_z80p_l",
    "body_cbs_head_x25p",
    "body_cbs_head_x30n",
    "body_cbs_neck1_x25n",
    "body_cbs_neck1_x40p",
    "body_cbs_neck1_y22n_r",
    "body_cbs_neck1_y22p_l",
    "body_cbs_neck1_z40n_l",
    "body_cbs_neck1_z40p_r",
    "body_cbs_shoulder_x30n_l",
    "body_cbs_shoulder_x30n_r",
    "body_cbs_shoulder_x30p_l",
    "body_cbs_shoulder_x30p_r",
    "body_cbs_shoulder_z55n_r",
    "body_cbs_shoulder_z55p_l",
    "body_cbs_upperarm_x95n_l",
    "body_cbs_upperarm_x95n_r",
    "body_cbs_upperarm_y110n_l",
    "body_cbs_upperarm_y110n_z40n_l",
    "body_cbs_upperarm_y110n_z90p_l",
    "Michael9_facs_cbs_CheekSquintL",
    "Michael9_facs_cbs_CheekSquintR",
    "Michael9_facs_cbs_MouthFrownL",
    "Michael9_facs_cbs_MouthFrownR",
    "Michael9_facs_cbs_MouthFunnelLowerL",
    "Michael9_facs_cbs_MouthFunnelLowerR",
    "Michael9_facs_cbs_MouthFunnelUpperL",
    "Michael9_facs_cbs_MouthFunnelUpperR",
    "Michael9_facs_cbs_MouthPurseLowerL",
    "Michael9_facs_cbs_MouthPurseLowerR",
    "Michael9_facs_cbs_MouthPurseUpperL",
    "Michael9_facs_cbs_MouthPurseUpperR",
    "Michael9_body_cbs_head_x25p",
    "Michael9_body_cbs_head_z20n",
    "Michael9_body_cbs_head_z20p",
    "Michael9_body_cbs_neck1_x25n",
    "Michael9_body_cbs_neck1_x40p",
    "Michael9_body_cbs_neck2_x24p",
    "Michael9_body_cbs_neck2_x27n",
    "Michael9_body_cbs_shoulder_z55n_r",
    "Michael9_body_cbs_shoulder_z55p_l",
    "Michael9_body_cbs_upperarm_y110n_l",
    "Michael9_body_cbs_upperarm_y110n_z40n_l",
    "Michael9_body_cbs_upperarm_y110n_z90p_l",
    "Michael9_body_cbs_upperarm_y110p_r",
    "Michael9_body_cbs_upperarm_y110p_z40p_r",
    "Michael9_body_cbs_upperarm_y110p_z90n_r",
    "Michael9_body_cbs_upperarm_z40n_l",
    "Michael9_body_cbs_upperarm_z40p_r",
    "Michael9_body_cbs_upperarm_z90n_r",
    "Michael9_body_cbs_upperarm_z90p_l",
    "Afraid",
    "Angry",
    "BareTeeth",
    "Bereft",
    "Bored",
    "Brow Down",
    "Brow Up",
    "BrowOuterUp",
    "BrowUp-Down",
    "BrowUp-DownL",
    "BrowUp-DownR",
    "Cheek Hollow",
    "Cheek Hollow Left",
    "Cheek Hollow Right",
    "Cheek Inflate Left",
    "Cheek Inflate Right",
    "Cheek Puff",
    "Cheek Puff Left",
    "Cheek Puff Right",
    "Cheek Squint",
    "Cheek Squint Left",
    "Cheek Squint Right",
    "CheeksPuff-Hollow",
    "Concentrate",
    "Confident",
    "Confused",
    "Contempt",
    "Desire",
    "Disgust",
    "Drunk",
    "Excitement",
    "Eye Blink",
    "Eye Blink Left",
    "Eye Blink Right",
    "Eye Crossed",
    "Fear",
    "Fierce",
    "Flirting",
    "Frown",
    "Glare",
    "Happy",
    "Ignore",
    "Ill",
    "Incredulous",
    "Irritated",
    "Jaw Forward-Recess",
    "Jaw Left-Right",
    "Jaw Open",
    "Jaw Open Wide",
    "Left Hand Fist",
    "Left Hand Grasp",
    "Left Hand Relax",
    "Left Hand Spread",
    "Mouth Close",
    "Mouth Frown",
    "Mouth Funnel",
    "Mouth Left-Right",
    "Mouth Press",
    "Mouth Smile",
    "Mouth Smile Left",
    "Mouth Smile Right",
    "Mouth Smile Widen",
    "Mouth Smile Widen Left",
    "Mouth Smile Widen Right",
    "Mouth Stretch",
    "Mouth Upper Up",
    "Nasal Compress",
    "Nose Sneer",
    "Pain",
    "Pleased",
    "Pouty",
    "Rage",
    "Right Hand Fist",
    "Right Hand Grasp",
    "Right Hand Relax",
    "Right Hand Spread",
    "Sad",
    "Sarcastic",
    "Scream",
    "Serious",
    "Shock",
    "Shoulders Shrug",
    "Silly",
    "Smile Full Face",
    "Smile Open Full Face",
    "Snarl",
    "Surprised",
    "Suspicious",
    "Tired",
    "Triumph",
    "Vis AA",
    "Vis EE",
    "Vis EH",
    "Vis ER",
    "Vis F",
    "Vis IH",
    "Vis IY",
    "Vis K",
    "Vis L",
    "Vis M",
    "Vis OW",
    "Vis S",
    "Vis SH",
    "Vis T",
    "Vis TH",
    "Vis UW",
    "Vis W",
    "Wink",
]

def editdistance(a, b):
    """A simple implementation of the Levenshtein edit distance."""
    m = len(a) + 1
    n = len(b) + 1
    dp = [[0 for _ in range(n)] for _ in range(m)]
    for i in range(1, m):
        dp[i][0] = i
    for j in range(1, n):
        dp[0][j] = j
    for i in range(1, m):
        for j in range(1, n):
            cost = 0 if a[i - 1] == b[j - 1] else 1
            dp[i][j] = min(dp[i - 1][j] + 1, dp[i][j - 1] + 1, dp[i - 1][j - 1] + cost)
    return dp[m - 1][n - 1]

audio2faceEmotionNamesToShapeKeys = {}
for emotion in audio2faceEmotionNames:
    min_distance = float("inf")
    best_match = None
    for shapekey in shape_keys_cleaned_with_expresions_visemes:
        distance = editdistance(emotion, shapekey)
        if distance < min_distance:
            min_distance = distance
            best_match = shapekey
    audio2faceEmotionNamesToShapeKeys[emotion] = best_match

print("Audio2Face Emotion Names to Shape Keys:")
print(audio2faceEmotionNamesToShapeKeys)

a2fEmotionNamesToShapeKeys = {
    "amazement": "Excitement",
    "anger": "Angry",
    "cheekiness": "Pouty",
    "disgust": "Disgust",
    "fear": "Fear",
    "grief": "Bereft",
    "joy": "Happy",
    "outofbreath": "Shocked",
    "pain": "Pain",
    "sadness": "Sad",
}

a2fBlendshapesToShapeKeys = {
    "eyeBlinkLeft": "Eye Blink Left",
    "eyeLookDownLeft": "facs_bs_EyeLookDownLeft",
    "eyeLookInLeft": "facs_bs_EyeLookInLeft",
    "eyeLookOutLeft": "facs_bs_EyeLookOutLeft",
    "eyeLookUpLeft": "facs_bs_EyeLookUpLeft",
    "eyeSquintLeft": "facs_bs_EyeSquintLeft",
    "eyeWideLeft": "eyeWideLeft",
    "eyeBlinkRight": "Eye Blink Right",
    "eyeLookDownRight": "facs_bs_EyeLookDownRight",
    "eyeLookInRight": "facs_bs_EyeLookInRight",
    "eyeLookOutRight": "facs_bs_EyeLookOutRight",
    "eyeLookUpRight": "facs_bs_EyeLookUpRight",
    "eyeSquintRight": "facs_bs_EyeSquintRight",
    "eyeWideRight": "eyeWideRight",
    "jawForward": "",
    "jawLeft": "facs_bs_JawLeft",
    "jawRight": "facs_bs_JawRight",
    "jawOpen": "Jaw Open",
    "mouthClose": "Mouth Close",
    "mouthFunnel": "Mouth Funnel",
    "mouthPucker": "",
    "mouthLeft": "facs_bs_MouthLeft",
    "mouthRight": "facs_bs_MouthRight",
    "mouthSmileLeft": "Mouth Smile Left",
    "mouthSmileRight": "Mouth Smile Right",
    "mouthFrownLeft": "Mouth Frown",
    "mouthFrownRight": "Mouth Frown",
    "mouthDimpleLeft": "",
    "mouthDimpleRight": "",
    "mouthStretchLeft": "Mouth Stretch",
    "mouthStretchRight": "Mouth Stretch",
    "mouthRollLower": "",
    "mouthRollUpper": "",
    "mouthShrugLower": "",
    "mouthShrugUpper": "",
    "mouthPressLeft": "Mouth Press",
    "mouthPressRight": "",
    "mouthLowerDownLeft": "",
    "mouthLowerDownRight": "",
    "mouthUpperUpLeft": "Mouth Upper Up",
    "mouthUpperUpRight": "",
    "browDownLeft": "facs_BrowDownLeft",
    "browDownRight": "facs_BrowDownRight",
    "browInnerUp": "",
    "browOuterUpLeft": "facs_BrowOuterUpLeft",
    "browOuterUpRight": "facs_BrowOuterUpRight",
    "cheekPuff": "Cheek Puff",
    "cheekSquintLeft": "Cheek Squint Left",
    "cheekSquintRight": "Cheek Squint Right",
    "noseSneerLeft": "Nose Sneer",
    "noseSneerRight": "Nose Sneer",
    "tongueOut": "",
}

shape_keys_with_body_morphs = [
    "Basic",
    "head_bs_AsymmetryBrowHeightLeft",
    "head_bs_AsymmetryBrowHeightRight",
    "head_bs_AsymmetryBrowSizeLeft",
    "head_bs_AsymmetryBrowSizeRight",
    "head_bs_AsymmetryCheekSizeLeft",
    "head_bs_AsymmetryCheekSizeRight",
    "head_bs_AsymmetryEars01Left",
    "head_bs_AsymmetryEars01Right",
    "head_bs_AsymmetryEars02Left",
    "head_bs_AsymmetryEars02Right",
    "head_bs_AsymmetryEars03Left",
    "head_bs_AsymmetryEars03Right",
    "head_bs_AsymmetryEarsPositionHeightLeft",
    "head_bs_AsymmetryEarsPositionHeightRight",
    "head_bs_AsymmetryEyelidsCreaseHeightLeft",
    "head_bs_AsymmetryEyelidsCreaseHeightRight",
    "head_bs_AsymmetryEyelidsLowerRelaxLeft",
    "head_bs_AsymmetryEyelidsLowerRelaxRight",
    "head_bs_AsymmetryEyelidsUpperRelaxLeft",
    "head_bs_AsymmetryEyelidsUpperRelaxRight",
    "head_bs_AsymmetryEyesAngleLeft",
    "head_bs_AsymmetryEyesAngleRight",
    "head_bs_AsymmetryEyesDepthLeft",
    "head_bs_AsymmetryEyesDepthRight",
    "head_bs_AsymmetryEyesHeightLeft",
    "head_bs_AsymmetryEyesHeightRight",
    "head_bs_AsymmetryEyesPositionWidthLeft",
    "head_bs_AsymmetryEyesPositionWidthRight",
    "head_bs_AsymmetryFaceHeartLeft",
    "head_bs_AsymmetryFaceHeartRight",
    "head_bs_AsymmetryFaceRoundLeft",
    "head_bs_AsymmetryFaceRoundRight",
    "head_bs_AsymmetryFaceSquareLeft",
    "head_bs_AsymmetryFaceSquareRight",
    "head_bs_AsymmetryJawHorizontalBalance",
    "head_bs_AsymmetryLipLowerThicknessLeft",
    "head_bs_AsymmetryLipLowerThicknessRight",
    "head_bs_AsymmetryLipUpperThicknessLeft",
    "head_bs_AsymmetryLipUpperThicknessRight",
    "head_bs_AsymmetryMouthAngleLeft",
    "head_bs_AsymmetryMouthAngleRight",
    "head_bs_AsymmetryMouthMidCurveLeft",
    "head_bs_AsymmetryMouthMidCurveRight",
    "head_bs_AsymmetryNoseBaseHorizontal",
    "head_bs_AsymmetryNoseBaseTwist",
    "head_bs_AsymmetryNoseBridgeHorizontal",
    "head_bs_AsymmetryNoseBridgeUpperHoriz",
    "head_bs_AsymmetryNoseRotateLeft",
    "head_bs_AsymmetryNoseRotateRight",
    "head_bs_AsymmetryNoseTipBalanceLeft",
    "head_bs_AsymmetryNoseTipBalanceRight",
    "head_bs_AsymmetryNoseWingHeightPosLeft",
    "head_bs_AsymmetryNoseWingHeightPosRight",
    "head_bs_AsymmetryNoseWingSizeLeft",
    "head_bs_AsymmetryNoseWingSizeRight",
    "head_cbs_AsymmetryEyelidsLowerRelaxLeft",
    "head_cbs_AsymmetryEyelidsLowerRelaxRight",
    "head_cbs_AsymmetryEyelidsUpperRelaxLeft",
    "head_cbs_AsymmetryEyelidsUpperRelaxRight",
    "facs_BrowDownLeft",
    "facs_BrowDownRight",
    "facs_bs_BrowInnerUpLeft",
    "facs_bs_BrowInnerUpRight",
    "facs_BrowOuterUpLeft",
    "facs_BrowOuterUpRight",
    "facs_bs_BrowSqueezeLeft",
    "facs_bs_BrowSqueezeRight",
    "facs_bs_CheekHollowLeft",
    "facs_bs_CheekHollowRight",
    "facs_bs_CheekInflateCounterLeft",
    "facs_bs_CheekInflateCounterRight",
    "facs_bs_CheekInflateLeft",
    "facs_bs_CheekInflateRight",
    "facs_bs_CheekPuffLeft",
    "facs_bs_CheekPuffRight",
    "facs_bs_CheekSquintLeft",
    "facs_bs_CheekSquintRight",
    "facs_bs_EarPullBackLeft",
    "facs_bs_EarPullBackRight",
    "facs_bs_EyeBlinkLeft",
    "facs_bs_EyeBlinkRight",
    "facs_bs_EyeCornerTightnessInnerLeft",
    "facs_bs_EyeCornerTightnessInnerRight",
    "facs_bs_EyeCornerTightnessOuterLeft",
    "facs_bs_EyeCornerTightnessOuterRight",
    "facs_bs_EyeLidCloseUpperLeft",
    "facs_bs_EyeLookDownLeft",
    "facs_bs_EyeLookDownRight",
    "facs_bs_EyeLookInLeft",
    "facs_bs_EyeLookInRight",
    "facs_bs_EyeLookOutLeft",
    "facs_bs_EyeLookOutRight",
    "facs_bs_EyeLookUpLeft",
    "facs_bs_EyeLookUpRight",
    "facs_bs_EyeSquintLeft",
    "facs_bs_EyeSquintRight",
    "facs_bs_EyelidCloseLowerLeft",
    "facs_bs_EyelidCloseLowerRight",
    "facs_bs_EyelidCloseUpperRight",
    "facs_bs_EyelidOpenLowerLeft",
    "facs_bs_EyelidOpenLowerRight",
    "facs_bs_EyelidOpenUpperLeft",
    "facs_bs_EyelidOpenUpperRight",
    "facs_bs_JawChinCompression",
    "facs_bs_JawClenchLeft",
    "facs_bs_JawClenchRight",
    "facs_bs_JawLeft",
    "facs_bs_JawOpen",
    "facs_bs_JawOpenWide",
    "facs_bs_JawRecess",
    "facs_bs_JawRight",
    "facs_bs_MouthBackLowerLeft",
    "facs_bs_MouthBackLowerRight",
    "facs_bs_MouthBackUpperLeft",
    "facs_bs_MouthBackUpperRight",
    "facs_bs_MouthCloseLowerLeft",
    "facs_bs_MouthCloseLowerRight",
    "facs_bs_MouthCloseUpperLeft",
    "facs_bs_MouthCloseUpperRight",
    "facs_bs_MouthCompressLowerLeft",
    "facs_bs_MouthCompressLowerRight",
    "facs_bs_MouthCompressUpperLeft",
    "facs_bs_MouthCompressUpperRight",
    "facs_bs_MouthCornerMoveFwd-BackLeft",
    "facs_bs_MouthCornerMoveFwd-BackRight",
    "facs_bs_MouthCornerMoveSide-SideLeft",
    "facs_bs_MouthCornerMoveSide-SideRight",
    "facs_bs_MouthCornerMoveUp-DownLeft",
    "facs_bs_MouthCornerMoveUp-DownRight",
    "facs_bs_MouthCornerTightnessLowerLeft",
    "facs_bs_MouthCornerTightnessLowerRight",
    "facs_bs_MouthCornerTightnessUpperLeft",
    "facs_bs_MouthCornerTightnessUpperRight",
    "facs_bs_MouthDimpleLeft",
    "facs_bs_MouthDimpleRight",
    "facs_bs_MouthForward-BackMiddleLower",
    "facs_bs_MouthForward-BackMiddleUpper",
    "facs_bs_MouthForwardLowerLeft",
    "facs_bs_MouthForwardLowerRight",
    "facs_bs_MouthForwardUpperLeft",
    "facs_bs_MouthForwardUpperRight",
    "facs_bs_MouthFrownLeft",
    "facs_bs_MouthFrownRight",
    "facs_bs_MouthFunnelLowerLeft",
    "facs_bs_MouthFunnelLowerRight",
    "facs_bs_MouthFunnelUpperLeft",
    "facs_bs_MouthFunnelUpperRight",
    "facs_bs_MouthLeft",
    "facs_bs_MouthLipsSide-SideLower",
    "facs_bs_MouthLipsSide-SideUpper",
    "facs_bs_MouthLipVolumeLowerLeft",
    "facs_bs_MouthLipVolumeLowerRight",
    "facs_bs_MouthLipVolumeUpperLeft",
    "facs_bs_MouthLipVolumeUpperRight",
    "facs_bs_MouthLowerDownLeft",
    "facs_bs_MouthLowerDownRight",
    "facs_bs_MouthPressLowerLeft",
    "facs_bs_MouthPressLowerRight",
    "facs_bs_MouthPressUpperLeft",
    "facs_bs_MouthPressUpperRight",
    "facs_bs_MouthPurseLowerLeft",
    "facs_bs_MouthPurseLowerRight",
    "facs_bs_MouthPurseUpperLeft",
    "facs_bs_MouthPurseUpperRight",
    "facs_bs_MouthRight",
    "facs_bs_MouthRollLowerLeft",
    "facs_bs_MouthRollLowerRight",
    "facs_bs_MouthRollUpperLeft",
    "facs_bs_MouthRollUpperRight",
    "facs_bs_MouthShrugLowerLeft",
    "facs_bs_MouthShrugLowerRight",
    "facs_bs_MouthShrugUpperLeft",
    "facs_bs_MouthShrugUpperRight",
    "facs_bs_MouthSmileLeft",
    "facs_bs_MouthSmileRight",
    "facs_bs_MouthSmileWidenLeft",
    "facs_bs_MouthSmileWidenRight",
    "facs_bs_MouthStickyLowerCenter",
    "facs_bs_MouthStickyLowerInnerLeft",
    "facs_bs_MouthStickyLowerInnerRight",
    "facs_bs_MouthStickyLowerOuterLeft",
    "facs_bs_MouthStickyLowerOuterRight",
    "facs_bs_MouthStickyUpperCenter",
    "facs_bs_MouthStickyUpperInnerLeft",
    "facs_bs_MouthStickyUpperInnerRight",
    "facs_bs_MouthStickyUpperOuterLeft",
    "facs_bs_MouthStickyUpperOuterRight",
    "facs_bs_MouthStretchLeft",
    "facs_bs_MouthStretchRight",
    "facs_bs_MouthUp-Down",
    "facs_bs_MouthUp-DownMiddleLower",
    "facs_bs_MouthUp-DownMiddleUpper",
    "facs_bs_MouthUpperUpLeft",
    "facs_bs_MouthUpperUpRight",
    "facs_bs_NasalCompressLeft",
    "facs_bs_NasalCompressRight",
    "facs_bs_NasalCreaseFlexLeft",
    "facs_bs_NasalCreaseFlexRight",
    "facs_bs_NasalFlareLeft",
    "facs_bs_NasalFlareRight",
    "facs_bs_NasalStretchLeft",
    "facs_bs_NasalStretchRight",
    "facs_bs_NeckFlexLeft",
    "facs_bs_NeckFlexRight",
    "facs_bs_NeckLarynxUp",
    "facs_bs_NeckMastoidFlexLeft",
    "facs_bs_NeckMastoidFlexRight",
    "facs_bs_NeckUnderChinFlex",
    "facs_bs_NoseSneerLeft",
    "facs_bs_NoseSneerRight",
    "facs_bs_NoseSneerUpperLeft",
    "facs_bs_NoseSneerUpperRight",
    "FACSDetails_facs_bs_BIU_BOULeft_HD2",
    "FACSDetails_facs_bs_BIU_BOURight_HD2",
    "FACSDetails_facs_bs_BrowDownLeft_HD2",
    "FACSDetails_facs_bs_BrowDownRight_HD2",
    "FACSDetails_facs_bs_BrowInnerUpLeft_HD2",
    "FACSDetails_facs_bs_BrowInnerUpRight_HD2",
    "FACSDetails_facs_bs_BrowOuterUpLeft_HD2",
    "FACSDetails_facs_bs_BrowOuterUpRight_HD2",
    "FACSDetails_facs_bs_BrowSqueezeLeft_HD2",
    "FACSDetails_facs_bs_BrowSqueezeRight_HD2",
    "FACSDetails_facs_bs_CheekSquintLeft_HD2",
    "FACSDetails_facs_bs_CheekSquintRight_HD2",
    "FACSDetails_facs_bs_EyeSquintLeft_HD2",
    "FACSDetails_facs_bs_EyeSquintRight_HD2",
    "FACSDetails_facs_bs_JawChinCompression_HD2",
    "FACSDetails_facs_bs_MouthFrownLeft_HD2",
    "FACSDetails_facs_bs_MouthFrownRight_HD2",
    "FACSDetails_facs_bs_MouthPurseLowerLeft_HD2",
    "FACSDetails_facs_bs_MouthPurseLowerRight_HD2",
    "FACSDetails_facs_bs_MouthPurseUpperLeft_HD2",
    "FACSDetails_facs_bs_MouthPurseUpperRight_HD2",
    "FACSDetails_facs_bs_MouthShrugLowerLeft_HD2",
    "FACSDetails_facs_bs_MouthShrugLowerRight_HD2",
    "FACSDetails_facs_bs_NoseSneerLeft_HD2",
    "FACSDetails_facs_bs_NoseSneerRight_HD2",
    "FACSDetails_facs_bs_NoseSneerUpperLeft_HD2",
    "FACSDetails_facs_bs_NoseSneerUpperRight_HD2",
    "body_bs_FlexBicepsL",
    "body_bs_FlexBicepsR",
    "body_bs_FlexCalfL",
    "body_bs_FlexCalfR",
    "body_bs_FlexGluteClenchL",
    "body_bs_FlexGluteClenchR",
    "body_bs_FlexHamstringL",
    "body_bs_FlexHamstringR",
    "body_bs_FlexQuadL",
    "body_bs_FlexQuadR",
    "body_bs_FlexShoulderUpperBackL",
    "body_bs_FlexShoulderUpperBackR",
    "body_bs_FlexTricepsL",
    "body_bs_FlexTricepsR",
    "body_bs_BreastsFlattenLeft",
    "body_bs_BreastsFlattenRight",
    "body_bs_BreastsHangForwardLeft",
    "body_bs_BreastsHangForwardRight",
    "body_cbs_foot_x45n_l",
    "body_cbs_foot_x45n_r",
    "body_cbs_foot_x65p_l",
    "body_cbs_foot_x65p_r",
    "body_cbs_foot_z45n_l",
    "body_cbs_foot_z45p_r",
    "body_cbs_forearm_y135n_l",
    "body_cbs_forearm_y135p_r",
    "body_cbs_forearm_y75n_l",
    "body_cbs_forearm_y75p_r",
    "body_cbs_hand_y28n_l",
    "body_cbs_hand_y28p_r",
    "body_cbs_hand_z70n_l",
    "body_cbs_hand_z70p_r",
    "body_cbs_hand_z80n_r",
    "body_cbs_hand_z80p_l",
    "body_cbs_head_x25p",
    "body_cbs_head_x30n",
    "body_cbs_neck1_x25n",
    "body_cbs_neck1_x40p",
    "body_cbs_neck1_y22n_r",
    "body_cbs_neck1_y22p_l",
    "body_cbs_neck1_z40n_l",
    "body_cbs_neck1_z40p_r",
    "body_cbs_pelvis_x25n",
    "body_cbs_pelvis_x25p",
    "body_cbs_shin_x155p_l",
    "body_cbs_shin_x155p_r",
    "body_cbs_shin_x90p_l",
    "body_cbs_shin_x90p_r",
    "body_cbs_shoulder_x30n_l",
    "body_cbs_shoulder_x30n_r",
    "body_cbs_shoulder_x30p_l",
    "body_cbs_shoulder_x30p_r",
    "body_cbs_shoulder_z55n_r",
    "body_cbs_shoulder_z55p_l",
    "body_cbs_spine1_x35p",
    "body_cbs_spine1_z15n_l",
    "body_cbs_spine1_z15p_r",
    "body_cbs_spine2_x40p",
    "body_cbs_spine2_z24n_l",
    "body_cbs_spine2_z24p_r",
    "body_cbs_spine3_x35p",
    "body_cbs_spine3_z20n_l",
    "body_cbs_spine3_z20p_r",
    "body_cbs_thigh_x115n_l",
    "body_cbs_thigh_x115n_r",
    "body_cbs_thigh_x115n_z90n_r",
    "body_cbs_thigh_x115n_z90p_l",
    "body_cbs_thigh_x35p_l",
    "body_cbs_thigh_x35p_r",
    "body_cbs_thigh_x90n_l",
    "body_cbs_thigh_x90n_r",
    "body_cbs_thigh_z90n_r",
    "body_cbs_thigh_z90p_l",
    "body_cbs_upperarm_x95n_l",
    "body_cbs_upperarm_x95n_r",
    "body_cbs_upperarm_y110n_l",
    "body_cbs_upperarm_y110n_z40n_l",
    "body_cbs_upperarm_y110n_z90p_l",
    "body_cbs_upperarm_y110p_r",
    "body_cbs_upperarm_y110p_z40p_r",
    "body_cbs_upperarm_y110p_z90n_r",
    "body_cbs_upperarm_z40n_l",
    "body_cbs_upperarm_z40p_r",
    "body_cbs_upperarm_z90n_r",
    "body_cbs_upperarm_z90p_l",
    "Michael9_facs_cbs_CheekSquintL",
    "Michael9_facs_cbs_CheekSquintR",
    "Michael9_facs_cbs_EyeBlinkL",
    "Michael9_facs_cbs_EyeBlinkR",
    "Michael9_facs_cbs_MouthFrownL",
    "Michael9_facs_cbs_MouthFrownR",
    "Michael9_facs_cbs_MouthFunnelLowerL",
    "Michael9_facs_cbs_MouthFunnelLowerR",
    "Michael9_facs_cbs_MouthFunnelUpperL",
    "Michael9_facs_cbs_MouthFunnelUpperR",
    "Michael9_facs_cbs_MouthPurseLowerL",
    "Michael9_facs_cbs_MouthPurseLowerR",
    "Michael9_facs_cbs_MouthPurseUpperL",
    "Michael9_facs_cbs_MouthPurseUpperR",
    "ProportionSmallerBO_body_cbs_spine1_x35p",
    "ProportionSmallerBO_body_cbs_spine1_z15n_l",
    "ProportionSmallerBO_body_cbs_spine1_z15p_r",
    "ProportionSmallerBO_body_cbs_spine2_x40p",
    "ProportionSmallerBO_body_cbs_spine2_z24n_l",
    "ProportionSmallerBO_body_cbs_spine2_z24p_r",
    "ProportionSmallerBO_body_cbs_spine3_x35p",
    "ProportionSmallerBO_body_cbs_spine3_z20n_l",
    "ProportionSmallerBO_body_cbs_spine3_z20p_r",
    "ProportionSmallerBO_body_cbs_thigh_z90n_r",
    "ProportionSmallerBO_body_cbs_thigh_z90p_l",
    "ProportionSmaller_body_cbs_spine1_x35p",
    "ProportionSmaller_body_cbs_spine1_z15n_l",
    "ProportionSmaller_body_cbs_spine1_z15p_r",
    "ProportionSmaller_body_cbs_spine2_x40p",
    "ProportionSmaller_body_cbs_spine2_z24n_l",
    "ProportionSmaller_body_cbs_spine2_z24p_r",
    "ProportionSmaller_body_cbs_spine3_x35p",
    "ProportionSmaller_body_cbs_spine3_z20n_l",
    "ProportionSmaller_body_cbs_spine3_z20p_r",
    "ProportionSmaller_body_cbs_thigh_z90n_r",
    "ProportionSmaller_body_cbs_thigh_z90p_l",
    "Michael9_body_cbs_head_x25p",
    "Michael9_body_cbs_head_z20n",
    "Michael9_body_cbs_head_z20p",
    "Michael9_body_cbs_neck1_x25n",
    "Michael9_body_cbs_neck1_x40p",
    "Michael9_body_cbs_neck2_x24p",
    "Michael9_body_cbs_neck2_x27n",
    "Michael9_body_cbs_shin_x155p_l",
    "Michael9_body_cbs_shin_x155p_r",
    "Michael9_body_cbs_shin_x90p_l",
    "Michael9_body_cbs_shin_x90p_r",
    "Michael9_body_cbs_shoulder_z55n_r",
    "Michael9_body_cbs_shoulder_z55p_l",
    "Michael9_body_cbs_spine1_x35p",
    "Michael9_body_cbs_spine1_z15n_l",
    "Michael9_body_cbs_spine1_z15p_r",
    "Michael9_body_cbs_spine2_x40p",
    "Michael9_body_cbs_spine3_x35p",
    "Michael9_body_cbs_thigh_x115n_l",
    "Michael9_body_cbs_thigh_x115n_r",
    "Michael9_body_cbs_thigh_x115n_z90n_r",
    "Michael9_body_cbs_thigh_x115n_z90p_l",
    "Michael9_body_cbs_thigh_x90n_l",
    "Michael9_body_cbs_thigh_x90n_r",
    "Michael9_body_cbs_thigh_x90n_shin_x90p_l",
    "Michael9_body_cbs_thigh_x90n_shin_x90p_r",
    "Michael9_body_cbs_thigh_z90n_r",
    "Michael9_body_cbs_thigh_z90p_l",
    "Michael9_body_cbs_upperarm_y110n_l",
    "Michael9_body_cbs_upperarm_y110n_z40n_l",
    "Michael9_body_cbs_upperarm_y110n_z90p_l",
    "Michael9_body_cbs_upperarm_y110p_r",
    "Michael9_body_cbs_upperarm_y110p_z40p_r",
    "Michael9_body_cbs_upperarm_y110p_z90n_r",
    "Michael9_body_cbs_upperarm_z40n_l",
    "Michael9_body_cbs_upperarm_z40p_r",
    "Michael9_body_cbs_upperarm_z90n_r",
    "Michael9_body_cbs_upperarm_z90p_l",
]

shape_keys_all_merged = [
    "body_cbs_pelvis_x25n",
    "facs_bs_MouthRollLowerLeft",
    "CheeksPuff-Hollow",
    "facs_bs_CheekInflateLeft",
    "head_bs_AsymmetryFaceHeartLeft",
    "head_bs_AsymmetryEyesHeightRight",
    "head_bs_AsymmetryCheekSizeRight",
    "FACSDetails_facs_bs_MouthShrugLowerLeft_HD2",
    "FACSDetails_facs_bs_JawChinCompression_HD2",
    "Mouth Press",
    "facs_bs_MouthCompressUpperLeft",
    "body_cbs_forearm_y75n_l",
    "facs_bs_MouthStickyUpperCenter",
    "facs_bs_JawLeft",
    "head_bs_AsymmetryNoseWingSizeRight",
    "facs_bs_MouthRollUpperRight",
    "facs_bs_MouthBackUpperRight",
    "facs_bs_JawClenchLeft",
    "facs_bs_CheekInflateRight",
    "facs_bs_EyeLookUpRight",
    "facs_bs_BrowSqueezeRight",
    "facs_bs_MouthLeft",
    "facs_bs_NoseSneerUpperLeft",
    "Concentrate",
    "Mouth Close",
    "Michael9_body_cbs_upperarm_y110n_l",
    "FACSDetails_facs_bs_BrowInnerUpRight_HD2",
    "body_cbs_spine3_x35p",
    "ProportionSmallerBO_body_cbs_spine1_z15n_l",
    "body_cbs_thigh_z90p_l",
    "head_bs_AsymmetryEyesHeightLeft",
    "Michael9_body_cbs_upperarm_y110n_z90p_l",
    "body_cbs_neck1_z40p_r",
    "Michael9_facs_cbs_MouthFrownL",
    "body_cbs_spine3_z20p_r",
    "facs_bs_NasalStretchRight",
    "head_bs_AsymmetryEyelidsUpperRelaxLeft",
    "FACSDetails_facs_bs_BIU_BOURight_HD2",
    "body_cbs_spine2_z24p_r",
    "Triumph",
    "Michael9_facs_cbs_MouthPurseLowerL",
    "Nasal Compress",
    "Ill",
    "Eye Crossed",
    "Michael9_body_cbs_shoulder_z55n_r",
    "Shock",
    "Michael9_body_cbs_upperarm_z90n_r",
    "ProportionSmaller_body_cbs_spine2_x40p",
    "body_cbs_upperarm_y110n_z90p_l",
    "head_bs_AsymmetryNoseRotateRight",
    "Michael9_body_cbs_spine1_z15n_l",
    "head_bs_AsymmetryLipLowerThicknessRight",
    "facs_bs_MouthStickyUpperOuterLeft",
    "Michael9_facs_cbs_MouthFunnelUpperL",
    "facs_BrowDownLeft",
    "Michael9_body_cbs_thigh_z90p_l",
    "facs_bs_MouthLowerDownRight",
    "facs_bs_MouthStickyLowerInnerRight",
    "Michael9_body_cbs_thigh_x115n_z90n_r",
    "Michael9_body_cbs_thigh_x115n_z90p_l",
    "FACSDetails_facs_bs_CheekSquintLeft_HD2",
    "facs_bs_MouthLipVolumeUpperLeft",
    "body_cbs_neck1_y22n_r",
    "facs_bs_MouthCornerTightnessLowerRight",
    "body_bs_FlexShoulderUpperBackR",
    "Suspicious",
    "Shoulders Shrug",
    "facs_bs_NeckFlexRight",
    "Glare",
    "FACSDetails_facs_bs_MouthPurseUpperLeft_HD2",
    "head_bs_AsymmetryMouthAngleLeft",
    "facs_bs_MouthLowerDownLeft",
    "Michael9_body_cbs_spine2_x40p",
    "Mouth Smile Right",
    "body_cbs_hand_z70p_r",
    "facs_bs_EyeLookInRight",
    "Jaw Open",
    "Left Hand Spread",
    "body_bs_FlexTricepsR",
    "head_bs_AsymmetryEyelidsLowerRelaxLeft",
    "Smile Full Face",
    "facs_bs_NoseSneerLeft",
    "facs_bs_NasalFlareRight",
    "body_cbs_foot_x45n_r",
    "FACSDetails_facs_bs_MouthPurseLowerRight_HD2",
    "ProportionSmaller_body_cbs_spine3_x35p",
    "facs_bs_EarPullBackLeft",
    "Pain",
    "facs_bs_JawOpenWide",
    "facs_bs_MouthBackLowerLeft",
    "Eye Blink Left",
    "Michael9_body_cbs_shin_x155p_l",
    "head_bs_AsymmetryEars02Right",
    "Michael9_body_cbs_upperarm_y110p_z90n_r",
    "Cheek Hollow",
    "facs_bs_MouthUp-DownMiddleUpper",
    "facs_bs_MouthRollUpperLeft",
    "body_cbs_shin_x90p_r",
    "body_cbs_spine1_x35p",
    "Michael9_body_cbs_shin_x90p_l",
    "facs_BrowDownRight",
    "facs_bs_BrowSqueezeLeft",
    "Michael9_body_cbs_thigh_x90n_shin_x90p_l",
    "body_bs_FlexShoulderUpperBackL",
    "Cheek Squint Right",
    "Jaw Left-Right",
    "facs_bs_MouthShrugLowerLeft",
    "FACSDetails_facs_bs_NoseSneerRight_HD2",
    "facs_bs_NasalCreaseFlexRight",
    "facs_bs_MouthStickyLowerInnerLeft",
    "facs_bs_MouthSmileWidenLeft",
    "head_bs_AsymmetryBrowHeightRight",
    "ProportionSmallerBO_body_cbs_thigh_z90n_r",
    "Flirting",
    "facs_bs_NeckMastoidFlexRight",
    "ProportionSmallerBO_body_cbs_spine1_z15p_r",
    "Vis W",
    "facs_bs_MouthCornerTightnessLowerLeft",
    "facs_bs_EyelidOpenLowerRight",
    "Right Hand Fist",
    "Mouth Smile Widen Left",
    "FACSDetails_facs_bs_BrowInnerUpLeft_HD2",
    "facs_bs_BrowInnerUpLeft",
    "Michael9_body_cbs_thigh_x115n_l",
    "facs_bs_MouthStretchRight",
    "body_cbs_pelvis_x25p",
    "Vis OW",
    "head_bs_AsymmetryNoseTipBalanceLeft",
    "body_bs_FlexQuadR",
    "facs_bs_MouthFunnelLowerRight",
    "Vis ER",
    "facs_bs_MouthStickyUpperInnerLeft",
    "body_cbs_thigh_x115n_r",
    "Cheek Squint",
    "Michael9_body_cbs_upperarm_z90p_l",
    "Michael9_body_cbs_spine1_x35p",
    "Brow Down",
    "ProportionSmaller_body_cbs_spine2_z24p_r",
    "Snarl",
    "facs_bs_MouthLipsSide-SideLower",
    "body_cbs_foot_x45n_l",
    "Vis EH",
    "head_bs_AsymmetryNoseTipBalanceRight",
    "facs_bs_MouthFunnelUpperLeft",
    "head_bs_AsymmetryCheekSizeLeft",
    "body_cbs_thigh_x115n_z90n_r",
    "ProportionSmallerBO_body_cbs_spine2_x40p",
    "head_bs_AsymmetryBrowSizeLeft",
    "body_bs_BreastsFlattenLeft",
    "FACSDetails_facs_bs_BrowSqueezeRight_HD2",
    "body_cbs_upperarm_y110n_l",
    "Cheek Hollow Left",
    "BareTeeth",
    "head_bs_AsymmetryEars01Left",
    "body_bs_BreastsFlattenRight",
    "Pleased",
    "body_cbs_foot_z45n_l",
    "head_bs_AsymmetryEyelidsLowerRelaxRight",
    "FACSDetails_facs_bs_BrowDownLeft_HD2",
    "Tired",
    "facs_bs_CheekSquintLeft",
    "facs_bs_EyeCornerTightnessInnerLeft",
    "Right Hand Spread",
    "body_cbs_shoulder_x30p_r",
    "Pouty",
    "Silly",
    "body_cbs_upperarm_y110n_z40n_l",
    "body_cbs_forearm_y75p_r",
    "head_bs_AsymmetryEyesPositionWidthRight",
    "Michael9_facs_cbs_MouthPurseUpperR",
    "facs_bs_EyelidOpenUpperLeft",
    "head_bs_AsymmetryEarsPositionHeightLeft",
    "body_cbs_spine2_x40p",
    "facs_bs_MouthForwardLowerLeft",
    "facs_bs_MouthPurseUpperRight",
    "body_bs_FlexGluteClenchL",
    "facs_bs_JawClenchRight",
    "body_bs_FlexTricepsL",
    "body_cbs_foot_z45p_r",
    "Vis S",
    "head_bs_AsymmetryBrowHeightLeft",
    "facs_bs_CheekPuffLeft",
    "Vis F",
    "facs_bs_EyelidOpenUpperRight",
    "Serious",
    "FACSDetails_facs_bs_BrowDownRight_HD2",
    "facs_bs_MouthCornerTightnessUpperLeft",
    "Incredulous",
    "body_bs_FlexBicepsR",
    "body_cbs_shoulder_x30n_l",
    "head_bs_AsymmetryNoseWingHeightPosLeft",
    "Michael9_body_cbs_head_z20p",
    "FACSDetails_facs_bs_BIU_BOULeft_HD2",
    "body_cbs_head_x25p",
    "Cheek Inflate Left",
    "facs_bs_MouthPressLowerRight",
    "Left Hand Fist",
    "facs_bs_MouthForwardUpperLeft",
    "facs_bs_MouthSmileWidenRight",
    "body_bs_FlexGluteClenchR",
    "facs_bs_EyeLookOutLeft",
    "FACSDetails_facs_bs_NoseSneerUpperLeft_HD2",
    "FACSDetails_facs_bs_MouthFrownRight_HD2",
    "ProportionSmaller_body_cbs_spine2_z24n_l",
    "body_cbs_upperarm_x95n_l",
    "body_cbs_thigh_x35p_r",
    "head_bs_AsymmetryEyesAngleRight",
    "ProportionSmallerBO_body_cbs_spine1_x35p",
    "Ignore",
    "head_bs_AsymmetryNoseBridgeUpperHoriz",
    "ProportionSmallerBO_body_cbs_thigh_z90p_l",
    "ProportionSmallerBO_body_cbs_spine3_z20p_r",
    "head_bs_AsymmetryLipUpperThicknessLeft",
    "Michael9_body_cbs_upperarm_z40n_l",
    "FACSDetails_facs_bs_BrowOuterUpRight_HD2",
    "facs_bs_JawOpen",
    "facs_bs_NeckMastoidFlexLeft",
    "facs_bs_EyelidCloseLowerRight",
    "Rage",
    "facs_bs_NasalFlareLeft",
    "Jaw Forward-Recess",
    "Vis SH",
    "Michael9_facs_cbs_MouthPurseUpperL",
    "Michael9_facs_cbs_MouthPurseLowerR",
    "facs_bs_MouthCornerMoveFwd-BackRight",
    "facs_bs_NeckFlexLeft",
    "Michael9_facs_cbs_MouthFunnelLowerL",
    "facs_bs_JawChinCompression",
    "body_bs_FlexBicepsL",
    "facs_bs_MouthSmileRight",
    "head_bs_AsymmetryNoseBridgeHorizontal",
    "BrowUp-DownL",
    "ProportionSmallerBO_body_cbs_spine3_z20n_l",
    "facs_bs_MouthPressUpperLeft",
    "Basic",
    "facs_bs_MouthCloseUpperRight",
    "facs_bs_MouthSmileLeft",
    "Sarcastic",
    "Desire",
    "Left Hand Relax",
    "body_cbs_upperarm_y110p_r",
    "facs_BrowOuterUpRight",
    "facs_bs_MouthLipsSide-SideUpper",
    "Michael9_body_cbs_neck2_x27n",
    "facs_bs_MouthStretchLeft",
    "head_bs_AsymmetryNoseBaseTwist",
    "facs_bs_NeckUnderChinFlex",
    "ProportionSmaller_body_cbs_thigh_z90n_r",
    "body_cbs_shin_x155p_r",
    "ProportionSmaller_body_cbs_thigh_z90p_l",
    "Vis T",
    "facs_bs_MouthPurseUpperLeft",
    "facs_bs_EyeCornerTightnessOuterLeft",
    "Michael9_body_cbs_spine3_x35p",
    "body_cbs_shoulder_x30n_r",
    "head_bs_AsymmetryMouthAngleRight",
    "head_bs_AsymmetryEars03Left",
    "Michael9_body_cbs_upperarm_y110n_z40n_l",
    "body_cbs_upperarm_z40p_r",
    "body_cbs_upperarm_y110p_z90n_r",
    "Vis L",
    "Michael9_body_cbs_spine1_z15p_r",
    "Cheek Puff Left",
    "body_cbs_upperarm_z90n_r",
    "Excitement",
    "body_cbs_hand_y28n_l",
    "facs_bs_CheekSquintRight",
    "body_cbs_shoulder_x30p_l",
    "Mouth Funnel",
    "facs_bs_MouthFunnelLowerLeft",
    "Fierce",
    "facs_bs_CheekInflateCounterRight",
    "facs_BrowOuterUpLeft",
    "Michael9_facs_cbs_CheekSquintL",
    "facs_bs_MouthForwardLowerRight",
    "Michael9_body_cbs_head_z20n",
    "facs_bs_CheekPuffRight",
    "body_cbs_thigh_x115n_l",
    "Mouth Smile Widen Right",
    "FACSDetails_facs_bs_EyeSquintLeft_HD2",
    "Michael9_body_cbs_shin_x155p_r",
    "facs_bs_MouthForward-BackMiddleLower",
    "ProportionSmallerBO_body_cbs_spine2_z24n_l",
    "facs_bs_MouthCornerMoveUp-DownRight",
    "facs_bs_MouthCloseLowerRight",
    "Jaw Open Wide",
    "facs_bs_MouthRight",
    "facs_bs_MouthForwardUpperRight",
    "Bored",
    "head_bs_AsymmetryEyesDepthRight",
    "facs_bs_MouthCompressLowerLeft",
    "facs_bs_MouthUp-Down",
    "body_cbs_neck1_y22p_l",
    "head_cbs_AsymmetryEyelidsLowerRelaxLeft",
    "facs_bs_MouthStickyLowerOuterRight",
    "Brow Up",
    "head_bs_AsymmetryNoseWingSizeLeft",
    "FACSDetails_facs_bs_MouthPurseUpperRight_HD2",
    "facs_bs_MouthPressLowerLeft",
    "body_cbs_shoulder_z55p_l",
    "body_cbs_neck1_x25n",
    "facs_bs_EarPullBackRight",
    "Michael9_facs_cbs_MouthFunnelUpperR",
    "facs_bs_EyeLidCloseUpperLeft",
    "facs_bs_MouthCornerMoveUp-DownLeft",
    "facs_bs_MouthLipVolumeLowerLeft",
    "Vis K",
    "head_bs_AsymmetryFaceHeartRight",
    "FACSDetails_facs_bs_EyeSquintRight_HD2",
    "facs_bs_MouthStickyLowerCenter",
    "facs_bs_NasalStretchLeft",
    "body_cbs_neck1_x40p",
    "facs_bs_NoseSneerUpperRight",
    "Michael9_body_cbs_upperarm_z40p_r",
    "head_bs_AsymmetryEyelidsCreaseHeightRight",
    "Michael9_body_cbs_neck1_x25n",
    "body_bs_BreastsHangForwardLeft",
    "Michael9_facs_cbs_CheekSquintR",
    "FACSDetails_facs_bs_NoseSneerLeft_HD2",
    "head_bs_AsymmetryEarsPositionHeightRight",
    "Surprised",
    "body_cbs_thigh_x90n_r",
    "facs_bs_MouthCornerMoveSide-SideLeft",
    "Nose Sneer",
    "Right Hand Grasp",
    "Mouth Upper Up",
    "Michael9_body_cbs_shin_x90p_r",
    "Frown",
    "head_bs_AsymmetryEyesAngleLeft",
    "facs_bs_MouthFrownRight",
    "Michael9_body_cbs_upperarm_y110p_r",
    "Mouth Stretch",
    "Afraid",
    "FACSDetails_facs_bs_MouthPurseLowerLeft_HD2",
    "head_cbs_AsymmetryEyelidsUpperRelaxRight",
    "Michael9_facs_cbs_EyeBlinkL",
    "head_bs_AsymmetryNoseWingHeightPosRight",
    "Left Hand Grasp",
    "head_bs_AsymmetryMouthMidCurveRight",
    "head_cbs_AsymmetryEyelidsUpperRelaxLeft",
    "body_cbs_spine3_z20n_l",
    "facs_bs_EyeCornerTightnessInnerRight",
    "Mouth Smile",
    "Irritated",
    "facs_bs_MouthCornerMoveFwd-BackLeft",
    "body_cbs_forearm_y135p_r",
    "facs_bs_MouthShrugUpperRight",
    "head_bs_AsymmetryFaceSquareLeft",
    "facs_bs_MouthBackLowerRight",
    "Michael9_facs_cbs_MouthFrownR",
    "facs_bs_MouthUp-DownMiddleLower",
    "body_cbs_spine1_z15n_l",
    "body_cbs_upperarm_z90p_l",
    "body_cbs_hand_z80n_r",
    "body_cbs_foot_x65p_r",
    "head_bs_AsymmetryNoseBaseHorizontal",
    "facs_bs_MouthUpperUpRight",
    "head_bs_AsymmetryFaceSquareRight",
    "Disgust",
    "facs_bs_EyeBlinkRight",
    "facs_bs_EyeLookDownRight",
    "body_cbs_head_x30n",
    "Michael9_facs_cbs_MouthFunnelLowerR",
    "Drunk",
    "body_cbs_upperarm_y110p_z40p_r",
    "body_cbs_thigh_x90n_l",
    "Michael9_body_cbs_thigh_x90n_shin_x90p_r",
    "Happy",
    "Bereft",
    "Mouth Smile Left",
    "body_bs_FlexQuadL",
    "body_cbs_shin_x155p_l",
    "body_cbs_shin_x90p_l",
    "head_bs_AsymmetryEars01Right",
    "facs_bs_BrowInnerUpRight",
    "facs_bs_EyeLookInLeft",
    "head_bs_AsymmetryLipLowerThicknessLeft",
    "body_cbs_thigh_x115n_z90p_l",
    "facs_bs_JawRecess",
    "body_cbs_hand_z70n_l",
    "ProportionSmallerBO_body_cbs_spine3_x35p",
    "body_cbs_hand_y28p_r",
    "facs_bs_EyeCornerTightnessOuterRight",
    "FACSDetails_facs_bs_CheekSquintRight_HD2",
    "facs_bs_EyeLookUpLeft",
    "Wink",
    "head_bs_AsymmetryEyelidsCreaseHeightLeft",
    "facs_bs_MouthFrownLeft",
    "body_bs_FlexHamstringR",
    "Vis TH",
    "facs_bs_MouthLipVolumeUpperRight",
    "Michael9_body_cbs_thigh_x90n_r",
    "head_bs_AsymmetryLipUpperThicknessRight",
    "facs_bs_NasalCreaseFlexLeft",
    "facs_bs_MouthRollLowerRight",
    "body_bs_FlexCalfL",
    "head_bs_AsymmetryNoseRotateLeft",
    "facs_bs_EyelidCloseUpperRight",
    "body_cbs_upperarm_x95n_r",
    "FACSDetails_facs_bs_BrowOuterUpLeft_HD2",
    "BrowUp-DownR",
    "head_bs_AsymmetryEyelidsUpperRelaxRight",
    "Michael9_facs_cbs_EyeBlinkR",
    "body_cbs_upperarm_z40n_l",
    "Confident",
    "facs_bs_MouthShrugUpperLeft",
    "Michael9_body_cbs_thigh_z90n_r",
    "body_cbs_hand_z80p_l",
    "Michael9_body_cbs_head_x25p",
    "facs_bs_CheekHollowLeft",
    "BrowUp-Down",
    "facs_bs_MouthCompressUpperRight",
    "facs_bs_JawRight",
    "Cheek Hollow Right",
    "body_bs_FlexCalfR",
    "body_bs_FlexHamstringL",
    "Contempt",
    "body_cbs_thigh_x35p_l",
    "Michael9_body_cbs_neck1_x40p",
    "facs_bs_MouthCloseUpperLeft",
    "head_bs_AsymmetryJawHorizontalBalance",
    "facs_bs_MouthPurseLowerRight",
    "Michael9_body_cbs_upperarm_y110p_z40p_r",
    "facs_bs_EyeSquintLeft",
    "Scream",
    "facs_bs_CheekInflateCounterLeft",
    "Vis IH",
    "head_cbs_AsymmetryEyelidsLowerRelaxRight",
    "facs_bs_CheekHollowRight",
    "ProportionSmaller_body_cbs_spine1_x35p",
    "facs_bs_EyeSquintRight",
    "Right Hand Relax",
    "facs_bs_NasalCompressRight",
    "head_bs_AsymmetryEyesPositionWidthLeft",
    "ProportionSmaller_body_cbs_spine1_z15p_r",
    "Vis UW",
    "facs_bs_MouthPurseLowerLeft",
    "facs_bs_MouthLipVolumeLowerRight",
    "Cheek Inflate Right",
    "body_bs_BreastsHangForwardRight",
    "facs_bs_MouthStickyLowerOuterLeft",
    "BrowOuterUp",
    "Fear",
    "facs_bs_EyelidOpenLowerLeft",
    "head_bs_AsymmetryBrowSizeRight",
    "facs_bs_MouthCornerMoveSide-SideRight",
    "facs_bs_NasalCompressLeft",
    "body_cbs_neck1_z40n_l",
    "FACSDetails_facs_bs_MouthFrownLeft_HD2",
    "facs_bs_MouthDimpleLeft",
    "head_bs_AsymmetryMouthMidCurveLeft",
    "facs_bs_MouthStickyUpperInnerRight",
    "Michael9_body_cbs_thigh_x115n_r",
    "Vis IY",
    "Mouth Left-Right",
    "Angry",
    "Cheek Squint Left",
    "FACSDetails_facs_bs_BrowSqueezeLeft_HD2",
    "Confused",
    "facs_bs_MouthPressUpperRight",
    "head_bs_AsymmetryFaceRoundRight",
    "body_cbs_spine1_z15p_r",
    "body_cbs_foot_x65p_l",
    "facs_bs_MouthStickyUpperOuterRight",
    "body_cbs_shoulder_z55n_r",
    "facs_bs_EyeLookOutRight",
    "facs_bs_EyelidCloseLowerLeft",
    "FACSDetails_facs_bs_MouthShrugLowerRight_HD2",
    "Vis M",
    "Mouth Smile Widen",
    "head_bs_AsymmetryEars03Right",
    "head_bs_AsymmetryEyesDepthLeft",
    "Michael9_body_cbs_thigh_x90n_l",
    "Sad",
    "FACSDetails_facs_bs_NoseSneerUpperRight_HD2",
    "Smile Open Full Face",
    "body_cbs_spine2_z24n_l",
    "facs_bs_MouthUpperUpLeft",
    "ProportionSmaller_body_cbs_spine3_z20p_r",
    "Cheek Puff Right",
    "Michael9_body_cbs_neck2_x24p",
    "head_bs_AsymmetryFaceRoundLeft",
    "facs_bs_NeckLarynxUp",
    "ProportionSmaller_body_cbs_spine1_z15n_l",
    "Mouth Frown",
    "Michael9_body_cbs_shoulder_z55p_l",
    "ProportionSmallerBO_body_cbs_spine2_z24p_r",
    "Cheek Puff",
    "facs_bs_NoseSneerRight",
    "facs_bs_EyeLookDownLeft",
    "facs_bs_MouthDimpleRight",
    "Eye Blink Right",
    "Eye Blink",
    "facs_bs_MouthForward-BackMiddleUpper",
    "facs_bs_MouthCompressLowerRight",
    "body_cbs_forearm_y135n_l",
    "facs_bs_MouthCloseLowerLeft",
    "Vis AA",
    "facs_bs_MouthShrugLowerRight",
    "facs_bs_MouthCornerTightnessUpperRight",
    "Vis EE",
    "ProportionSmaller_body_cbs_spine3_z20n_l",
    "facs_bs_MouthBackUpperLeft",
    "head_bs_AsymmetryEars02Left",
    "facs_bs_MouthFunnelUpperRight",
    "body_cbs_thigh_z90n_r",
    "facs_bs_EyeBlinkLeft",
]

